name: Rust CI

on:
  pull_request:
    branches:
      - master
      - nightly

  push:
    branches:
      - master
      - nightly

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    name: Check & Test (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check code
        run: cargo check --all-targets

      - name: Test code
        run: cargo test --all-features

  build_windows:
    name: Check & Test (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check code
        run: cargo check --all-targets

      - name: Test code
        run: cargo test --all-features

  build_macos:
    name: Check & Test (macOS)
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check code
        run: cargo check --all-targets

      - name: Test code
        run: cargo test --all-features
